apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: connect-wipe
  namespace: connect
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: NAMESPACE
              value: connect
            image: gcr.io/connect-sandbox-224121/connect-wipe
            imagePullPolicy: Always
            name: wiper
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 1 * * 1
  successfulJobsHistoryLimit: 3
  suspend: false
